const fs = require('fs');
let data = JSON.parse(fs.readFileSync('Colab-Server.ipynb', 'utf8'));

for (let cell of data.cells) {
  if (cell.cell_type === 'code' && (cell.source.join('').includes('Start Ngrok') || cell.source.join('').includes('Cloudflare Tunnel'))) {
    cell.source = [
      "# 5. Start Cloudflare Tunnel and Auto-Update Vercel!\n",
      "import subprocess\n",
      "import time\n",
      "import re\n",
      "import requests\n",
      "\n",
      "vercel_token = None\n",
      "vercel_project_id = None\n",
      "\n",
      "try:\n",
      "    with open('/content/mediatools/backend/.env', 'r') as f:\n",
      "        for line in f:\n",
      "            if line.startswith('VERCEL_TOKEN='):\n",
      "                vercel_token = line.strip().split('=', 1)[1]\n",
      "            elif line.startswith('VERCEL_PROJECT_ID='):\n",
      "                vercel_project_id = line.strip().split('=', 1)[1]\n",
      "except Exception as e:\n",
      "    pass\n",
      "\n",
      "print(\"🌐 Downloading Cloudflare Tunnel...\")\n",
      "!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64\n",
      "!chmod +x cloudflared-linux-amd64\n",
      "\n",
      "print(\"🚀 Starting Cloudflare Tunnel in the background...\")\n",
      "subprocess.run(\"nohup ./cloudflared-linux-amd64 tunnel --url http://localhost:5000 > cloudflare.log 2>&1 &\", shell=True)\n",
      "\n",
      "print(\"⏳ Waiting 8 seconds for Cloudflare to generate the link...\")\n",
      "time.sleep(8)\n",
      "\n",
      "public_url = None\n",
      "try:\n",
      "    with open(\"cloudflare.log\", \"r\") as f:\n",
      "        log_content = f.read()\n",
      "    match = re.search(r'https://[a-zA-Z0-9.-]+\\.trycloudflare\\.com', log_content)\n",
      "    if match:\n",
      "        public_url = match.group(0)\n",
      "except Exception as e:\n",
      "    print(f\"Could not read log: {e}\")\n",
      "\n",
      "if public_url:\n",
      "    print(\"=\"*60)\n",
      "    print(f\"🎯 YOUR BACKEND API IS LIVE AT: {public_url}\")\n",
      "    print(\"=\"*60)\n",
      "    \n",
      "    if vercel_token and vercel_project_id:\n",
      "        print(\"🔄 Auto-updating Vercel with new URL...\")\n",
      "        headers = {'Authorization': f'Bearer {vercel_token}'}\n",
      "        # 1. Get existing env vars to find the ID of NEXT_PUBLIC_API_URL\n",
      "        resp = requests.get(f'https://api.vercel.com/v9/projects/{vercel_project_id}/env', headers=headers)\n",
      "        env_id = None\n",
      "        if resp.status_code == 200:\n",
      "            for env in resp.json().get('envs', []):\n",
      "                if env['key'] == 'NEXT_PUBLIC_API_URL':\n",
      "                    env_id = env['id']\n",
      "                    break\n",
      "        \n",
      "        # 2. Update or Create\n",
      "        if env_id:\n",
      "            patch_resp = requests.patch(f'https://api.vercel.com/v9/projects/{vercel_project_id}/env/{env_id}', headers=headers, json={'value': public_url})\n",
      "            if patch_resp.status_code in [200, 201]:\n",
      "                print(\"✅ Updated existing Vercel Env Variable!\")\n",
      "        else:\n",
      "            post_resp = requests.post(f'https://api.vercel.com/v10/projects/{vercel_project_id}/env', headers=headers, json={'key': 'NEXT_PUBLIC_API_URL', 'value': public_url, 'type': 'encrypted', 'target': ['production', 'preview']})\n",
      "            if post_resp.status_code in [200, 201]:\n",
      "                print(\"✅ Created new Vercel Env Variable!\")\n",
      "        \n",
      "        # 3. Trigger Deploy\n",
      "        print(\"🚀 Triggering Vercel Redeployment...\")\n",
      "        deploy_resp = requests.post(f'https://api.vercel.com/v13/deployments', headers=headers, json={'name': 'mediatoolkit', 'project': vercel_project_id, 'target': 'production'})\n",
      "        if deploy_resp.status_code in [200, 201]:\n",
      "            print(\"✅ Vercel is now rebuilding! It will be ready in ~2 minutes.\")\n",
      "        else:\n",
      "            print(f\"⚠️ Failed to trigger deploy: {deploy_resp.text}\")\n",
      "    else:\n",
      "        print(\"⚠️ VERCEL_TOKEN or VERCEL_PROJECT_ID not found in .env. Skipping auto-update.\")\n",
      "else:\n",
      "    print(\"❌ Failed to get Cloudflare URL.\")\n",
      "\n",
      "# Start the Node.js backend server\n",
      "print(\"\\n📜 STREAMING LIVE SERVER LOGS BELOW...\")\n",
      "print(\"-\"*60)\n",
      "!npm start\n"
    ];
  }
}

fs.writeFileSync('Colab-Server.ipynb', JSON.stringify(data, null, 2), 'utf8');
console.log('Updated Colab-Server.ipynb to use Cloudflare and Vercel Auto-Update');
