import puppeteer from 'puppeteer-extra';
import StealthPlugin from 'puppeteer-extra-plugin-stealth';
import fs from 'fs';
import path from 'path';
import os from 'os';

puppeteer.use(StealthPlugin());

// Common realistic user agents
const USER_AGENTS = [
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:121.0) Gecko/20100101 Firefox/121.0',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0'
];

function getRandomDelay(min: number, max: number): Promise<void> {
  const delay = Math.floor(Math.random() * (max - min + 1)) + min;
  return new Promise(r => setTimeout(r, delay));
}

/**
 * The generated cookie jar. Lives inside /tmp so it survives hot-restarts
 * on Render (the filesystem is ephemeral but /tmp lasts the container's life).
 * On Windows (local dev), it goes into the backend directory.
 */
const COOKIE_FILE = os.platform() === 'win32'
  ? path.join(__dirname, '..', '..', 'cookies.txt')
  : path.join(os.tmpdir(), 'yt-cookies.txt');

let isRefreshing = false;
let lastRefresh = 0;

/**
 * Convert puppeteer cookies into yt-dlp's expected Netscape format.
 */
function formatCookiesToNetscape(cookies: any[]): string {
  let netscape = `# Netscape HTTP Cookie File\n# Automatically generated by MediaTools cookieManager\n# Do not edit manually.\n\n`;
  for (const cookie of cookies) {
    const domain = cookie.domain.startsWith('.') ? cookie.domain : `.${cookie.domain}`;
    const includeSubDomain = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const cookiePath = cookie.path;
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expiry = Math.round(cookie.expires || Date.now() / 1000 + 86400 * 365);
    const name = cookie.name;
    const value = cookie.value;
    netscape += `${domain}\t${includeSubDomain}\t${cookiePath}\t${secure}\t${expiry}\t${name}\t${value}\n`;
  }
  return netscape;
}

/**
 * Launch headless Chromium, visit YouTube, accept the consent dialog if
 * shown, watch a few seconds of a popular video (to earn non-bot cookies),
 * and then dump the resulting cookies into a Netscape jar file.
 *
 * On Render the Dockerfile installs system Chromium; locally it uses
 * Puppeteer's bundled version.
 */
export async function refreshYouTubeCookies(): Promise<boolean> {
  if (isRefreshing) {
    console.log('[CookieManager] Refresh already in progress, skipping');
    return false;
  }
  isRefreshing = true;
  console.log('[CookieManager] Starting headless cookie refresh...');

  let browser;
  try {
    browser = await puppeteer.launch({
      headless: true,
      executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || undefined,
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-accelerated-2d-canvas',
        '--disable-gpu',
        '--window-size=1280,720',
      ],
      // On low-memory servers (Render 512MB), keep protocolTimeout generous
      protocolTimeout: 90000,
    });

    const page = await browser.newPage();

    // Randomize User Agent
    const randomUA = USER_AGENTS[Math.floor(Math.random() * USER_AGENTS.length)];
    await page.setUserAgent(randomUA);
    
    // Randomize Viewport slightly
    const randomWidth = Math.floor(Math.random() * (1920 - 1024 + 1)) + 1024;
    const randomHeight = Math.floor(Math.random() * (1080 - 768 + 1)) + 768;
    await page.setViewport({ width: randomWidth, height: randomHeight });

    // Block heavy resources to keep memory usage low
    await page.setRequestInterception(true);
    page.on('request', (req: any) => {
      if (['image', 'stylesheet', 'font', 'media'].includes(req.resourceType())) {
        req.abort();
      } else {
        req.continue();
      }
    });

    // Step 1: Visit YouTube homepage to pick up initial cookies
    console.log('[CookieManager] Navigating to youtube.com...');
    await page.goto('https://www.youtube.com', {
      waitUntil: 'domcontentloaded',
      timeout: 60000,
    });
    
    await getRandomDelay(2000, 5000); // Human-like delay

    // Step 2: Accept consent dialog if it appears (EU / GDPR)
    try {
      const acceptBtn = await page.waitForSelector(
        'button[aria-label="Accept all"], button[aria-label="Accept the use of cookies and other data for the purposes described"]',
        { timeout: 4000 }
      );
      if (acceptBtn) {
        await getRandomDelay(1000, 2500); // Delay before clicking
        await acceptBtn.click();
        await getRandomDelay(2000, 4000); // Delay after clicking
        console.log('[CookieManager] Accepted consent dialog');
      }
    } catch {
      // No consent dialog — fine
    }

    // Step 3: Navigate to a popular video to trigger full cookie issuance
    // YouTube issues more robust cookies (VISITOR_INFO1_LIVE, GPS, etc.) on video pages
    console.log('[CookieManager] Loading a video page for cookie enrichment...');
    try {
      await page.goto('https://www.youtube.com/watch?v=jNQXAC9IVRw', {
        waitUntil: 'domcontentloaded',
        timeout: 30000,
      });
      // Wait a moment for YouTube to set all cookies (human-like viewing time)
      await getRandomDelay(4000, 8000);
    } catch (e) {
      console.warn('[CookieManager] Video page navigation failed, using homepage cookies');
    }

    // Step 4: Extract cookies
    const cookies = await page.cookies('https://www.youtube.com');
    if (cookies.length === 0) {
      throw new Error('No cookies extracted from YouTube');
    }

    // Step 5: Write Netscape-format cookie file
    const netscapeCookies = formatCookiesToNetscape(cookies);
    fs.writeFileSync(COOKIE_FILE, netscapeCookies, { mode: 0o600 });
    lastRefresh = Date.now();

    const relevantCookieNames = cookies.map(c => c.name).filter(n =>
      ['VISITOR_INFO1_LIVE', 'YSC', 'GPS', 'PREF', 'SID', 'HSID', 'SSID', 'LOGIN_INFO', '__Secure-1PSID'].includes(n)
    );
    console.log(`[CookieManager] ✓ Saved ${cookies.length} cookies (includes: ${relevantCookieNames.join(', ') || 'visitor cookies'})`);
    console.log(`[CookieManager] Cookie file: ${COOKIE_FILE}`);

    return true;
  } catch (error: any) {
    console.error('[CookieManager] ✗ Failed to refresh cookies:', error.message);
    return false;
  } finally {
    if (browser) {
      try { await browser.close(); } catch { }
    }
    isRefreshing = false;
  }
}

/**
 * Returns the path to the current cookie jar, or null if none exists.
 */
export function getActiveCookieFile(): string | null {
  if (fs.existsSync(COOKIE_FILE)) {
    const stats = fs.statSync(COOKIE_FILE);
    // Consider cookies stale after 2 hours
    if (Date.now() - stats.mtimeMs > 2 * 60 * 60 * 1000) {
      console.log('[CookieManager] Cookie file is stale (>2h), triggering background refresh');
      refreshYouTubeCookies().catch(() => {});
    }
    return COOKIE_FILE;
  }
  return null;
}

/**
 * Boot-time setup: generate cookies immediately, then refresh every 30 minutes.
 * Safe to call multiple times — the interval is only set once.
 */
let intervalHandle: NodeJS.Timeout | null = null;
export function startCookieManagerLoop() {
  if (intervalHandle) return;

  // On server (Linux), refresh cookies automatically via Puppeteer.
  // On local dev (Windows), skip — cookies from browser or manual file work better.
  const isServer = os.platform() !== 'win32';

  if (isServer) {
    console.log('[CookieManager] Starting automatic cookie refresh loop (every 30m)');
    // Initial fetch after a short delay to let the server bind its port first
    setTimeout(() => {
      refreshYouTubeCookies().catch(e => console.error('[CookieManager] Initial refresh failed:', e));
    }, 5000);

    intervalHandle = setInterval(() => {
      refreshYouTubeCookies().catch(e => console.error('[CookieManager] Periodic refresh failed:', e));
    }, 30 * 60 * 1000);
  } else {
    console.log('[CookieManager] Skipping auto-refresh on local dev (use YOUTUBE_COOKIES_FILE or YOUTUBE_COOKIES_B64)');
  }
}
